Repository BrainJS/brain.js, pull requests merged in 2020-10, with the labels that each got.

#607 convert reccurrent/matrix to ts
  src/recurrent/matrix/add-b.ts
  src/recurrent/matrix/add.ts
  src/recurrent/matrix/all-ones.ts
  src/recurrent/matrix/clone-negative.ts
  src/recurrent/matrix/clone.ts
  src/recurrent/matrix/copy.js
  src/recurrent/matrix/copy.ts
  src/recurrent/matrix/equation.ts
  src/recurrent/matrix/index.ts
  src/recurrent/matrix/max-i.ts
  src/recurrent/matrix/multiply-b.ts
  src/recurrent/matrix/multiply-element-b.ts
  src/recurrent/matrix/multiply-element.ts
  src/recurrent/matrix/multiply.ts
  src/recurrent/matrix/ones-matrix.ts
  src/recurrent/matrix/random-matrix.ts
  src/recurrent/matrix/random-n-matrix.js
  src/recurrent/matrix/random-n-matrix.ts
  src/recurrent/matrix/relu-b.ts
  src/recurrent/matrix/relu.ts
  src/recurrent/matrix/row-pluck-b.ts
  src/recurrent/matrix/row-pluck.ts
  src/recurrent/matrix/sample-i.ts
  src/recurrent/matrix/sigmoid-b.ts
  src/recurrent/matrix/sigmoid.ts
  src/recurrent/matrix/softmax.js
  src/recurrent/matrix/softmax.ts
  src/recurrent/matrix/tanh-b.ts
  src/recurrent/matrix/tanh.ts
Labels: ready, review

#612 Convert likely to typescript
  __tests__/likely.ts
  src/index.ts
  src/likely.ts
Labels: review

#610 Convert traverse-layers-from, traverse-layers-excluding-from, and to-svg from JS to TS
  src/utilities/to-svg.ts
  src/utilities/traverse-layers-excluding-from.ts
  src/utilities/traverse-layers-from.js
  src/utilities/traverse-layers-from.ts
Labels: blocked

#613 update leaky-relu function
  src/neural-network.js
Labels: ready

#599 Convert 2 files to Typescript
  src/index.ts
  src/utilities/array-lookup-table.js
  src/utilities/array-lookup-table.ts
  src/utilities/data-formatter.ts
Labels: ready, review
